buildscript {
    apply from: "gradle/repos.gradle"
    dependencies {
        classpath 'com.adarshr:gradle-test-logger-plugin:4.0.0'
    }
}

plugins {
    id 'java-library'
    id 'maven-publish' // 1. Apply the plugin
    id 'com.google.protobuf' version '0.9.5'
}

apply plugin: "idea"

apply from: "version.gradle"

subprojects {

    if (!new File(project.projectDir, 'build.gradle').exists()) {
        println "Disable build project: ${project.name}"
        tasks.each { it.enabled = false }
        return
    }

    apply from: "${rootDir}/gradle/libs.gradle"
    apply from: "${rootDir}/gradle/common.gradle"
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    //apply plugin: com.funext.gradle.support.JavaSupport
    //apply plugin: com.funext.gradle.support.EclipseSupport
    //apply plugin: com.funext.gradle.support.PublishSupport

    apply plugin: 'com.adarshr.test-logger'
    println "config subproject: ${project.name}"

    group = "com.cetrax"
    version = rootProject.version

    afterEvaluate {
        println("beforeEvaluate: ${name}, hasProto: ${new File(projectDir, "main/proto").isDirectory()}")
        if (new File(projectDir, "main/proto").isDirectory()) {
            protobuf {
                protoc {
                    artifact = libs.google_protoc //"com.google.protobuf:protoc:3.25.8"
                }
                plugins {
                    grpc {
                        artifact = libs.grpc_gen
                    }
                }
                generateProtoTasks {
                    all().each { task ->
                        task.builtins {
                            java { option 'lite' }
                        }
                        task.plugins {
                            grpc { option 'lite' }
                        }
                    }
                }
            }
        }
    }

    jar {
        manifest {
            attributes(
                    'Implementation-Title': project.name,
                    'Implementation-Version': project.version,
                    'Implementation-Vendor': 'Funext',
                    'Implementation-Vendor-Id': 'com.cetrax',
                    'Implementation-Vendor-Url': 'http://funext.io',
                    'Specification-Title': project.name,
                    'Specification-Version': project.version,
                    'Specification-Vendor': 'Cetrax')
        }
    }

    //tasks.getByName('publish')?.dependsOn("jar")
    //println("--------" + tasks.getByName('publish')+ "------------")
    project.afterEvaluate {
        publishing {
            publications {
                mavenJava(MavenPublication) {
                    pom {
                        name = 'Cetrax AOP - ' + project.name
                        description = project.description
                        url = "${rootDir}/build/pom"

                        organization {
                            name = 'Cetrax'
                            url = 'https://funext.io'
                        }

                        licenses {
                            license {
                                name = 'GNU Affero General Public License version 3'
                                url = 'https://www.gnu.org/licenses/agpl-3.0.html'
                                distribution = 'repo'
                            }
                        }
                    }
                }
            }
            repositories {

                maven {
                    def mPath = "${rootDir}/../repo/${baseVersion}/${version.endsWith('SNAPSHOT') ? 'snapshots' : 'releases'}"
                    println("publish to:: ${mPath}/${project.group.toString().replaceAll("\\.", "/")}/${project.name}")
                    name = 'myRepo'
                    url = mPath
                }
                /*
              tomcat {
                D:\\dev\\apache-tomcat-9.0.73\\webapps\\ROOT\\WEB-INF\\lib
              }*/
            }
        }
        test {
            failOnNoDiscoveredTests = false
            useJUnitPlatform()
        }
    }
}


apply from: "gradle/deps-versions.gradle"
